"""Session-C gate: docs/api-consistency.md never drifts from the code.

The page is generated by ``tools/gen_api_consistency.py``; this test
regenerates it in memory and compares. If it fails, run:
    python tools/gen_api_consistency.py
and commit the refreshed page.
"""
import importlib.util
import os

_ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), os.pardir))


def _load_generator():
    path = os.path.join(_ROOT, "tools", "gen_api_consistency.py")
    spec = importlib.util.spec_from_file_location("gen_api_consistency", path)
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


def test_api_consistency_page_is_current():
    mod = _load_generator()
    expected = mod.build_page()
    page_path = os.path.join(_ROOT, "docs", "api-consistency.md")
    assert os.path.isfile(page_path), "docs/api-consistency.md is missing"
    actual = open(page_path, encoding="utf-8").read()
    assert actual == expected, (
        "docs/api-consistency.md is stale -- regenerate with "
        "`python tools/gen_api_consistency.py` and commit it.")


def test_fit_apply_symmetry_has_no_exceptions():
    mod = _load_generator()
    offenders = [name for name, params in mod._unique_functions()
                 if "params" in params and "return_params" not in params]
    assert not offenders, offenders
