"""Auto-generate docs/api-consistency.md -- the public-API consistency table.

Run from the repo root:
    python tools/gen_api_consistency.py

The table is regenerated from live introspection of ``dextra.__all__`` so it
can never drift from the code; ``tests/test_api_consistency_page.py`` fails
if the committed page is stale.
"""
from __future__ import annotations

import inspect
import os

FLAGS = ["show", "plot", "return_df", "return_fig", "return_params",
         "params", "df_name", "decimals", "inplace", "protect"]

HEADER = """# API consistency

*Generated by `python tools/gen_api_consistency.py` -- do not edit by hand.*

Every public dextra function shares one flag vocabulary. `Y` = the function
accepts the flag; `-` = the flag does not apply (justified under
[Documented exceptions](#documented-exceptions)).

"""


def _unique_functions():
    import dextra as dx
    seen = {}
    for name in sorted(dx.__all__):
        obj = getattr(dx, name, None)
        if not callable(obj) or inspect.isclass(obj) or id(obj) in seen:
            continue
        try:
            sig = inspect.signature(obj)
        except (TypeError, ValueError):
            continue
        seen[id(obj)] = (name, set(sig.parameters))
    return sorted(seen.values())


def build_page() -> str:
    fns = _unique_functions()
    lines = [HEADER]
    lines.append("| function | " + " | ".join(FLAGS) + " |")
    lines.append("|---" * (len(FLAGS) + 1) + "|")
    for name, params in fns:
        cells = ["Y" if f in params else "-" for f in FLAGS]
        lines.append(f"| `{name}` | " + " | ".join(cells) + " |")

    lines.append("")
    lines.append("## Coverage per flag")
    lines.append("")
    lines.append("| flag | functions carrying it |")
    lines.append("|---|---|")
    n = len(fns)
    for f in FLAGS:
        c = sum(1 for _, p in fns if f in p)
        lines.append(f"| `{f}` | {c}/{n} |")

    lines.append("")
    lines.append("## Documented exceptions")
    lines.append("")
    no_show = [name for name, p in fns if "show" not in p]
    no_dfname = [name for name, p in fns if "df_name" not in p]
    lines.append(
        f"- Without `show` / `df_name`: "
        f"{', '.join(f'`{x}`' for x in sorted(set(no_show + no_dfname)))} -- "
        "zero-argument discoverability helpers (nothing to report on).")
    lines.append(
        "- `inplace` exists only on the four column-writing transforms "
        "(`transform`, `scale`, `bin`, `encode`); inside `featpipe` it "
        "defaults to `True` (0.6.0).")
    lines.append(
        "- `protect` exists on the selectors (`relevance`, `redundancy`) and "
        "`featpipe`, where auto-selection could otherwise swallow a target.")
    lines.append(
        "- Every function accepting `params` also accepts `return_params` "
        "(fit/apply symmetry holds with zero exceptions).")
    lines.append("")
    return "\n".join(lines)


def main() -> None:
    out = os.path.join(os.path.dirname(__file__), os.pardir,
                       "docs", "api-consistency.md")
    with open(os.path.abspath(out), "w", encoding="utf-8", newline="\n") as fh:
        fh.write(build_page())
    print(f"wrote {os.path.abspath(out)}")


if __name__ == "__main__":
    main()
