"""Interactive dashboard generator for dextra - Phase 10 (final) of the Roadmap.

The Streamlit RENDERER over the neutral composition layer
(:mod:`dextra._compose`). :func:`dash` GENERATES a self-contained Streamlit app
that re-runs dextra's analyses live under user controls -- the interactive
sibling of the Phase-9 HTML report. It COMPUTES NOTHING NEW: the dashboard's tabs
are the same ``_compose`` section builders the report uses, rendered to Streamlit
widgets instead of to HTML.

Design highlights (see DASHBOARD_PHILOSOPHY.md):

* One call -> one runnable ``dashboard_app.py`` + a sidecar data file (parquet /
  csv by default; pickle opt-in) + a ``*_meta.json`` reproducibility manifest. ``output_dir``
  collects them in one folder.
* Reuse verbatim: every tab is a ``_compose`` builder; no analysis is
  re-implemented (and the dashboard no longer depends on the report renderer).
* Streamlit is an OPTIONAL, lazy ``dash`` extra: imported only inside
  :func:`_build_dashboard` and the opt-in auto-launch. The renderer takes the
  Streamlit module as an ordinary dependency, so it is testable with a stub.
* The generated app checks its dependencies and data file up front with a clear
  message; section/tab isolation keeps it usable; the input DataFrame is never
  mutated (the sidecar is a faithful copy).

Stage 10.1 - app scaffold + data handoff + Overview / Data-quality tabs ;
10.2 - Univariate / Bivariate tabs ; 10.3 - optional Model tab + launch ;
hardening - neutral compose layer, output_dir, parquet, reproducibility manifest.
"""

from __future__ import annotations

import base64
import json
import os
import sys
import warnings
from datetime import datetime, timezone
from typing import Optional

import pandas as pd

from ._utils import _ensure_pandas, get_variable_name
from ._version import __version__

_TAB_LABELS = {
    "overview": "Overview",
    "quality": "Data quality",
    "univariate": "Univariate",
    "bivariate": "Bivariate",
    "model": "Model",
}

_DATA_EXT = {"pickle": "_data.pkl", "csv": "_data.csv", "parquet": "_data.parquet"}


# ---------------------------------------------------------------------------
# Small local helpers
# ---------------------------------------------------------------------------

def _now_iso() -> str:
    return datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")


def _append_audit(out: pd.DataFrame, entry: dict) -> None:
    out.attrs.setdefault("dextra_audit", [])
    out.attrs["dextra_audit"] = list(out.attrs["dextra_audit"])
    out.attrs["dextra_audit"].append(entry)


def _tab_keys(include_model: bool):
    from ._compose import _SECTION_ORDER
    return [k for k in _SECTION_ORDER if k != "model" or include_model]


def _have_parquet_engine() -> bool:
    """True when a parquet engine (pyarrow / fastparquet) is importable."""
    for mod in ("pyarrow", "fastparquet"):
        try:
            __import__(mod)
            return True
        except ImportError:
            continue
    return False


def _require_parquet_engine():
    """Confirm a parquet engine is importable, with a clear error if not."""
    if not _have_parquet_engine():
        raise ValueError(
            "dash: data_format='parquet' needs a parquet engine. Install one "
            "with `pip install \"dextra[perf]\"` (pyarrow), or use "
            "data_format='csv'."
        )


# ---------------------------------------------------------------------------
# The renderer -- runs inside the generated Streamlit app (and in tests with a
# stubbed ``streamlit``). Reuses the neutral _compose section builders verbatim.
# ---------------------------------------------------------------------------

def _build_dashboard(
    df,
    *,
    target: Optional[str] = None,
    include_model: bool = False,
    max_hist: int = 24,
    top_cat: int = 10,
    theme: str = "light",
    title: Optional[str] = None,
):
    """Render the dextra dashboard with Streamlit (imported lazily).

    Reuses ``_compose._BUILDERS``: each section's table is shown with
    ``st.dataframe``, its figure with ``st.image`` and its ``Decision:`` line as
    an info caption. A tab whose builder raises is isolated with a warning.
    """
    import streamlit as st

    from ._compose import _BUILDERS
    df = _ensure_pandas(df)
    if title is None:
        title = "dextra dashboard"
    try:
        st.set_page_config(page_title=title, layout="wide")
    except Exception:  # noqa: BLE001 - set_page_config is best-effort / one-shot
        pass
    st.title(title)
    st.caption(f"{len(df):,} rows x {df.shape[1]} columns - generated by dextra "
               f"v{__version__}")

    cols = list(df.columns)
    st.sidebar.header("Controls")
    options = ["(none)"] + cols
    default_idx = options.index(target) if target in cols else 0
    chosen = st.sidebar.selectbox("Target column (optional)", options,
                                  index=default_idx)
    target = None if chosen == "(none)" else chosen
    include_model = st.sidebar.checkbox("Include model section",
                                        value=bool(include_model))
    max_hist = int(st.sidebar.slider("Max histogram columns", 1, 50,
                                     int(max_hist)))
    top_cat = int(st.sidebar.slider("Top categorical columns", 1, 30,
                                    int(top_cat)))

    ctx = {"target": target, "include_model": include_model,
           "max_hist": max_hist, "top_cat": top_cat, "decimals": 4}

    keys = [k for k in _BUILDERS if k != "model" or include_model]
    tabs = st.tabs([_TAB_LABELS.get(k, k.title()) for k in keys])
    for tab, key in zip(tabs, keys):
        with tab:
            try:
                _name, blocks = _BUILDERS[key](df, ctx)
                for subtitle, table, img, decision, note in blocks:
                    if subtitle:
                        st.subheader(subtitle)
                    if note:
                        st.caption(note)
                    if decision:
                        st.info(f"Decision: {decision}")
                    if table is not None:
                        st.dataframe(table, use_container_width=True)
                    if img is not None:
                        st.image(base64.b64decode(img),
                                 use_container_width=True)
            except Exception as exc:  # noqa: BLE001 - tab isolation by design
                st.warning(f"Section '{key}' skipped: {exc}")


# ---------------------------------------------------------------------------
# Generated-app source + launch
# ---------------------------------------------------------------------------

def _render_app_source(data_basename, app_basename, data_format, target,
                       include_model, max_hist, top_cat, theme, title,
                       meta_line) -> str:
    return (
        "# Auto-generated by dextra dx.dash -- DO NOT EDIT BY HAND.\n"
        f"# Run with:  streamlit run {app_basename}\n"
        f"# {meta_line}\n"
        "import os\n"
        "import sys\n\n"
        "_HERE = os.path.dirname(os.path.abspath(__file__))\n"
        f"_DATA = os.path.join(_HERE, {data_basename!r})\n"
        f"_FORMAT = {data_format!r}\n\n"
        "try:\n"
        "    import pandas as pd\n"
        "    from dextra.dashboard import _build_dashboard\n"
        "except ImportError as exc:  # pragma: no cover\n"
        "    sys.stderr.write(\n"
        "        'This dashboard needs dextra and Streamlit. Install with:\\n'\n"
        "        '    pip install \"dextra[dash]\"\\n'\n"
        "        f'(import error: {exc})\\n')\n"
        "    raise SystemExit(1) from exc\n\n"
        "if not os.path.exists(_DATA):  # pragma: no cover\n"
        "    sys.stderr.write(f'Dashboard data file not found: {_DATA}\\n')\n"
        "    raise SystemExit(1)\n\n\n"
        "def _load():\n"
        "    if _FORMAT == 'csv':\n"
        "        return pd.read_csv(_DATA)\n"
        "    if _FORMAT == 'parquet':\n"
        "        return pd.read_parquet(_DATA)\n"
        "    return pd.read_pickle(_DATA)\n\n\n"
        "_build_dashboard(\n"
        "    _load(),\n"
        f"    target={target!r},\n"
        f"    include_model={bool(include_model)!r},\n"
        f"    max_hist={int(max_hist)!r},\n"
        f"    top_cat={int(top_cat)!r},\n"
        f"    theme={theme!r},\n"
        f"    title={title!r},\n"
        ")\n"
    )


def _launch(app_path) -> bool:
    """Best-effort ``streamlit run`` in a child process (opt-in)."""
    try:
        import subprocess

        import streamlit  # noqa: F401
        subprocess.Popen([sys.executable, "-m", "streamlit", "run", app_path])
        return True
    except Exception:  # noqa: BLE001 - launching is best-effort
        return False


# ===========================================================================
# 10  dash  --  generate a self-contained interactive Streamlit dashboard
# ===========================================================================

def dash(
    df: pd.DataFrame,
    *,
    out: str = "dashboard_app.py",
    output_dir: Optional[str] = None,
    target: Optional[str] = None,
    include_model: bool = False,
    launch: bool = False,
    data_format: str = "auto",
    max_hist: int = 24,
    top_cat: int = 10,
    theme: str = "light",
    return_params: bool = False,
    show: bool = True,
    df_name: Optional[str] = None,
):
    """Generate a self-contained interactive Streamlit dashboard in one call.

    Writes a thin ``dashboard_app.py``, a sidecar data file (``parquet`` when
    an engine is available, else ``csv``; ``pickle`` only on request), and a
    ``*_meta.json``
    reproducibility manifest (dextra / Python / pandas versions, settings).
    Running ``streamlit run dashboard_app.py`` renders the dextra dashboard: the
    same sections as :func:`edareport` (Overview, Data quality, Univariate,
    Bivariate, and an optional Model tab), made interactive via a sidebar. It
    computes nothing new -- it reuses the neutral ``_compose`` section builders.

    By default ``dash`` only generates and returns the app path
    (``launch=False``). Pass ``output_dir=`` to collect every output in one
    folder. Streamlit is the optional ``dash`` extra, imported lazily; the input
    DataFrame is never mutated (the sidecar is a copy).

    Parameters
    ----------
    df : pandas.DataFrame
        The data to explore. Never mutated.
    out : str
        App file name (or path). With ``output_dir`` only the basename is used.
    output_dir : str, optional
        Directory to write the app, data and metadata into (created if needed).
    target : str, optional
        Default target column for the bivariate / model tabs.
    include_model : bool
        Default state of the include-model toggle (the model tab needs a target
        and scikit-learn).
    launch : bool
        Also run ``streamlit run <app>`` in a child process.
    data_format : {"auto", "parquet", "csv", "pickle"}
        Sidecar format. ``auto`` (default) resolves to ``parquet`` when an
        engine (e.g. pyarrow) is importable, else ``csv``. ``parquet`` is
        portable + typed; ``csv`` is portable but loses dtypes; ``pickle``
        preserves dtypes with no dependency but can execute arbitrary code
        when loaded -- it is opt-in and emits a security ``UserWarning``.
    max_hist, top_cat : int
        Defaults for the histogram-column and categorical-column caps.
    theme : str
        Visual theme hint (``"light"``).
    return_params : bool
        Return the JSON-safe build manifest instead of the app path.
    show : bool
        Print the one-line ``Decision:`` summary.
    df_name : str, optional
        Name used in the title / audit (inferred when omitted).

    Returns
    -------
    str or dict
        The app path, or -- when ``return_params=True`` -- the manifest.

    Examples
    --------
    >>> dx.dash(df)                                   # writes dashboard_app.py
    >>> dx.dash(df, output_dir='dashboard', target='churn', include_model=True)
    >>> dx.dash(df, data_format='parquet', launch=True)
    """
    df = _ensure_pandas(df)
    if df_name is None:
        df_name = get_variable_name(df, depth=2)
    data_format = str(data_format).lower()
    if data_format not in ("auto", *_DATA_EXT):
        raise ValueError(
            f"dash: data_format must be one of {('auto', *_DATA_EXT)}, "
            f"got {data_format!r}.")
    if target is not None and target not in df.columns:
        raise KeyError(f"dash: target={target!r} not found in df.")
    if data_format == "auto":  # safe default: typed parquet, else plain csv
        data_format = "parquet" if _have_parquet_engine() else "csv"
    elif data_format == "pickle":
        warnings.warn(
            "dash: data_format='pickle' writes a pickle sidecar; pickle can "
            "execute arbitrary code when loaded, so share it only with "
            "trusted parties. Prefer 'parquet' (typed) or 'csv' (portable).",
            UserWarning, stacklevel=2)
    if data_format == "parquet":
        _require_parquet_engine()

    title = f"dextra dashboard - {df_name}"

    # Resolve output locations (optionally inside a dedicated folder).
    app_basename = os.path.basename(out)
    if output_dir is not None:
        os.makedirs(output_dir, exist_ok=True)
        app_path = os.path.join(output_dir, app_basename)
    else:
        app_path = out
    app_dir = os.path.dirname(app_path) or "."
    stem = os.path.splitext(app_basename)[0]
    data_name = stem + _DATA_EXT[data_format]
    data_path = os.path.join(app_dir, data_name)
    meta_path = os.path.join(app_dir, f"{stem}_meta.json")

    # Write the sidecar data (a faithful copy; df is never mutated).
    if data_format == "csv":
        df.to_csv(data_path, index=False)
    elif data_format == "parquet":
        df.to_parquet(data_path, index=False)
    else:
        df.to_pickle(data_path)

    generated_at = _now_iso()
    meta_line = (f"dextra={__version__}  python={sys.version.split()[0]}  "
                 f"pandas={pd.__version__}  generated={generated_at}")
    app_src = _render_app_source(
        data_name, app_basename, data_format, target, bool(include_model),
        int(max_hist), int(top_cat), theme, title, meta_line)
    with open(app_path, "w", encoding="utf-8") as fh:
        fh.write(app_src)

    tab_keys = _tab_keys(bool(include_model))
    metadata = {
        "function": "dash",
        "dextra_version": __version__,
        "python_version": sys.version.split()[0],
        "pandas_version": pd.__version__,
        "generated_at": generated_at,
        "app": app_path,
        "data": data_path,
        "data_format": data_format,
        "settings": {"target": target, "include_model": bool(include_model),
                     "max_hist": int(max_hist), "top_cat": int(top_cat),
                     "theme": theme},
        "tabs": [_TAB_LABELS[k] for k in tab_keys],
        "n_rows": int(len(df)), "n_cols": int(df.shape[1]),
    }
    with open(meta_path, "w", encoding="utf-8") as fh:
        json.dump(metadata, fh, indent=2)

    launched = _launch(app_path) if launch else False
    decision = (f"Dashboard written to '{app_path}' (+ data '{data_path}', "
                f"metadata '{meta_path}'). Run: streamlit run {app_path}"
                + ("  [launched]" if launched else "") + ".")

    out_copy = df.copy()
    out_copy.attrs = dict(df.attrs)
    _append_audit(out_copy, {
        "stage": "dashboard", "function": "dash",
        "timestamp": generated_at,
        "params": {"app": app_path, "data": data_path, "meta": meta_path,
                   "data_format": data_format, "target": target,
                   "include_model": bool(include_model)},
        "decision": decision,
    })

    if show:
        print(f"Decision: {decision}")

    if return_params:
        return {
            "function": "dash",
            "out": app_path,
            "data_path": data_path,
            "meta_path": meta_path,
            "data_format": data_format,
            "target": target,
            "include_model": bool(include_model),
            "tabs": metadata["tabs"],
            "metadata": {"n_rows": int(len(df)), "n_cols": int(df.shape[1]),
                         "launched": bool(launched), "theme": theme,
                         "dextra_version": __version__,
                         "python_version": metadata["python_version"],
                         "pandas_version": metadata["pandas_version"]},
            "version": __version__,
            "generated_at": generated_at,
        }
    return app_path


# Short alias, consistent with the underscore-free Phase 8 / 9 / 10 naming.
dashapp = dash
